### ISSUE TITLE
attach eth to bmv2 switch

### ISSUE THREAD

**Issue by bijutalukdar** [p4lang/p4c-bm#14]
Hi ,

I have attached a eth0 (real netdev interface of nic ) to the bmv2(c++) switch.  I did that by passing the eth0 as a parameter along with the json file to the switch, while configuring the switch with the compiled p4 program. Now I want to know in which port in the bmv2 switch will  receive the packets. I mean is there a mapping like  the following. I assumed this kind of mapping as I saw something similar in one of the tutorial slide.

app        switch(bmv2)
 veth0-->veth1 (port0)
 veth2-->veth3 (port1)
 veth4-->veth5 (port2)
 veth6-->veth7 (port3)

Also could someone point me to the source code file where  veth1, veth3, veth5 are instantiated in the bmv2 switch.

**Comment by antoninbas** [comment]
This question should have been asked in the behavioral-model repository.

By default, we use libpcap to read packets from interfaces. This means that you can attach pretty much any interface to bmv2.
The script to create veths is copied in several repositories, this is one possible link: https://github.com/p4lang/behavioral-model/blob/master/tools/veth_setup.sh

**Comment by bijutalukdar** [comment]
Hi,
Thanks for the reply. Sorry for posting the question in the wrong repository. I have re-posted it in the correct repository.
