### ISSUE TITLE
width_spec not properly handled by the compiler

### ISSUE THREAD

**Issue by ryzhyk** [p4lang/p4c-bm#40]
The P4 Language Specification document defines the following syntax for bit-vector constants:
`const_value ::= [ "+" | - ] [ width_spec ] unsigned_value`

However, the width_spec part does not seem to be supported by the compiler.  For example, it refuses to parse the following line: 
`modify_field(eth.etherType, 16'0xffff)`
but has no problems with:
`modify_field(eth.etherType, 0xffff)`

I also notice that the compiler supports the following syntax that is not described in the spec:
`modify_field(eth.etherType, 0xff ++ 0xff)`

Is this bitvector concatenation?  Should it be included in the language spec?

**Comment by antoninbas** [comment]
This is a (p4-hlir) [https://github.com/p4lang/p4-hlir] issue, not a bmv2 backend issue.
- explicit width specification is indeed not supported (except in field lists)
- this is just a guess but `0xff ++ 0xff` is probably interpreted as `0xff + (+0xff)`. Expressions as primitive arguments are actually supported by the compiler, so this is equivalent to `modify_field(eth.etherType, 0x1fe)`

**Comment by ryzhyk** [comment]
Thanks!  My problem then is that the arithmetic in P4 appears to be incomplete.  For example, I do not see how to, e.g., simulate the concatenation operation with what is currently supported.  However, this is offtopic here.  I will take my question to the P4 mailing list.

**Comment by antoninbas** [comment]
Closing this as it is a p4-hlir issue
