### ISSUE TITLE
What does PD stand for in this repository?

### ISSUE THREAD

**Issue by hamkuu** [p4lang/p4c-bm#69]

**Comment by antoninbas** [comment]
It stands for "Program-Dependent" or "P4-Dependent". We usually talk about the PD interface or the PD library. This is auto-generated code (from the P4 program) that lets the control-plane program the data-plane (e.g. methods to populate tables). The interface is supposed to be target-independent (i.e. work on every target: software switch, ASICs...).
This repository includes the templates for the PD library. When you run p4c-bm, the code is generated from the P4 program using these templates.
You can then compile this code yourself, but the p4-build repo (https://github.com/p4lang/p4-build) includes some makefiles to help you run p4c-bm and compile the generated PD code into a library.

**Comment by drobinkent** [comment]
Is there any example program about how to using the PD interface.

**Comment by antoninbas** [comment]
The control-plane stack written for switch.p4 uses the PD interface which is generated for this P4 program. See some PD method calls here for example: https://github.com/p4lang/switch/blob/master/switchapi/src/switch_pd.c
