### ISSUE TITLE
Explicit bit-widths cause parse error

### ISSUE THREAD

**Issue by jrmcclurg** [p4lang/p4c-bm#85]
Using p4c-bmv2 (1.3.0-28cdcef0), expressions such as the following compile just fine:

`add_to_field(routing_metadata.test, 1 + ((b + 0xFFFFFFFF) & 0xFFFFFFFF & (routing_metadata.temp)))`

But if I add a bit-width specifier to any integer constant (e.g., 32'0xFFFFFFFF), I get a parse error.

**Comment by antoninbas** [comment]
I think the compiler frontend doesn't support bitwidth specifiers, except for constants in field lists, even though the spec dictates it.

**Comment by jrmcclurg** [comment]
Ok thanks for the info. In that case, I'm a bit confused how to achieve the proper bitwidths within expressions. The spec indicates that expressions acquire the width of the widest constant, so wouldn't something like `(1 << 3)` evaluate to `0`, since neither constant is wider than 2 bits? Do I need to do something like `((1 & 0xFF) << 3)` to force the `1` to a larger width (e.g., 8 bits for `0xFF`)?

**Comment by antoninbas** [comment]
bmv2 performs arbitrary arithmetic, with the appropriate bitwidth being enforced only when the result is written to its final destination (e.g. field). It is up to the P4 compiler to adapt to this by emitting whichever code is necessary to achieve a behavior consistent with the spec.

This compiler (p4c-bmv2) will simply leverage bmv2's default behavior and will not try to enforce anything else. In this respect, it does not conform to the P4_14 spec. However, I believe the new compiler (p4lang/p4c) introduces masking operations on intermediate values (when evaluating expressions) to conform to the P4_16 spec (not sure about P4_14). I encourage you to generate the bmv2 JSON with both compilers, look at the differences in the files and maybe run them in bmv2 to observe the differences.

Regarding your example, I am not sure you have it right, even for P4_16. I believe `1 << 3` will be evaluated at compile time to `4w8` (or `4'8` in P4_14). I think a better example may be `f1 + f2`, where both `f1` and `f2` have P4_16 types `bit<8>`. I believe that if `f1 = f2 = 128` then `f1 + f2` should evaluate to `0` (you can test it with p4lang/p4c).

**Comment by jrmcclurg** [comment]
Ok this makes sense. Thanks very much for the help, I appreciate it.
